spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: ginlon

mybatis:
  configuration:
    map-underscore-to-camel-case: true # 下划线命名和驼峰命名的自动转换